### ISSUE TITLE
TODO: tasks and feature

### ISSUE THREAD

**Issue by 1dot75cm** [1dot75cm/dnf-plugin-lait#1]
Lait 是一个 DNF Plugin，是直接从 spec 构建/安装 rpm 包的解决方案。相对于分发 rpm 包来说，ship spec 有以下优势：
- 更轻量：不需要服务器资源，损耗更小；
- 可定制：spec 可以在编译前进行修改，添加需要的 flag；
- 避免协议限制：可以避免 Fedora 严格的协议限制。

TODO:
- [ ] edit spec before build
- [ ] rebuild, update, list function
- [ ] zh_CN translate
- [ ] some bug...
- [ ] FUR (Fedora User Repository)

其他新特性？ @FZUG @nrechn
